### ISSUE TITLE
docker - tomcat accessible but vcf-miner cannot be found

### ISSUE THREAD

**Issue by colindaven** [Steven-N-Hart/vcf-miner#3]
Hi,

I am using the docker version on ubuntu 16.04 64 bit.

I can access the tomcat server via a webbrowser but cannot access vcf-miner, no matter how long I wait.

How can I diagnose if the vcf-miner app is actually starting within the docker container correctly ?

I get a tomcat webpage

http://myip:7777/

I get a tomcat 404 vcf-miner 

http://myip:7777/vcf-miner/

HTTP Status 404 - /vcf-miner/ 

Any ideas ?

Thanks Colin

**Comment by dbrawand** [comment]
Same here. Can reproduce on Arch, Ubuntu, and MacOS.

**Comment by Steven-N-Hart** [comment]
Can you verify you have a mongod instance running in the background?

**Comment by dbrawand** [comment]
I am running the docker image from your docker hub repo. Mongo is running in the container and the mongoshell is accessible. Tomcat is running and the root address yields the tomcat webpage. Can you confirm this image should work? I rebuilt the image and encounter the same problem. Could be a problem on my side...

**Comment by colindaven** [comment]
Ditto. I'd say this is a ports problem, as I now have alternative software running on port 8080 (this wasn't there before however).

Can you recommend an alternative port for this command and explain where to make the changes in the docker image (I assume in interactive mode?) ?

Command:
docker run -e NO_LDAP=1 -d -p 8888:8000 stevenhart/vcf-miner:latest /home/start.sh


Thanks

**Comment by Steven-N-Hart** [comment]
Apologies for taking so long, but I am looking into it.

**Comment by Steven-N-Hart** [comment]
OK. I've updated the README.  You should now be able to start it without any problems.

**Comment by dbrawand** [comment]
I just rebuilt the docker image and the problem still persists. Using the docker image i can access the root page but not vcf-miner (404). Same issue with the provided docker image from docker hub.

**Comment by Steven-N-Hart** [comment]
can you let me know what commit you are running off of?

**Comment by Steven-N-Hart** [comment]
OK. I have updated the readme and build specifications.  This should resolve your problem.  Can you comment when you try it out?
